# Configuration KENOBI_TOOLS - GitLab uniquement
# 1. Copiez ce fichier vers config.yaml
# 2. Remplacez les URLs par vos instances
# 3. Configurez vos tokens dans le fichier .env

gitlab:
  url: "https://gitlab.votre-entreprise.com"
  token: "${GITLAB_TOKEN}"

extraction:
  batch_size: 50
  delay_between_calls: 1
  timeout: 30

filters:
  date_from: "2024-01-01"
  date_to: null
